server:
  port: 8080

spring:
  application:
    name: spring-boot-auth-boilerplate

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:boilerplate}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

auth:
  token:
    type: fernet
    access:
      duration: 1m
    refresh:
      duration: 10d

    fernet:
      secret: ${AUTH_TOKEN_FERNET_SECRET}

  anonymous:
    enabled: true
    email:
      domain: boilerplate.ercan.dev

  google:
    enabled: true
    client-id: ${AUTH_GOOGLE_CLIENT_ID}
    issuers: https://accounts.google.com
    jwk-url: https://www.googleapis.com/oauth2/v3/certs

  apple:
    enabled: true
    client-id: ${AUTH_APPLE_CLIENT_ID}
    issuers: https://appleid.apple.com
    jwk-url: https://appleid.apple.com/auth/keys

ratelimit:
  storage-type: inmemory
  ip-header-name: X-Forwarded-For
  trusted-proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
  policies:
    anonymous-login-success:
      ip:
        enabled: true
        limit: 5
        window: 24h

      global:
        enabled: true
        limit: 100
        window: 24h

    refresh-token-success:
      ip:
        enabled: true
        limit: 3
        window: 60s

    refresh-token-fail:
      ip:
        enabled: true
        limit: 5
        window: 24h

    apple-login-fail:
      ip:
        enabled: true
        limit: 5
        window: 24h

    google-login-fail:
      ip:
        enabled: true
        limit: 5
        window: 24h
