server:
  port: 8080

spring:
  application:
    name: spring-boot-auth-boilerplate

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:boilerplate}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: 60s

auth:
  token:
    type: fernet # fernet or jwt
    access:
      duration: 1m
      cleaner-job:
        cron: "0 0 * * * *"
        fetch-count: 10
        max-iteration: 50
    refresh:
      duration: 10d
      cleaner-job:
        cron: "0 10 * * * *"
        fetch-count: 10
        max-iteration: 50

    fernet:
      secret: ${AUTH_TOKEN_FERNET_SECRET}

    jwt:
      secret: ${AUTH_TOKEN_JWT_SECRET}
      issuer: ${AUTH_TOKEN_JWT_ISSUER}

  anonymous:
    enabled: true
    email:
      domain: boilerplate.ercan.dev

  email:
    enabled: true

  google:
    enabled: true
    client-id: ${AUTH_GOOGLE_CLIENT_ID}
    issuers: https://accounts.google.com
    jwk-url: https://www.googleapis.com/oauth2/v3/certs

  apple:
    enabled: true
    client-id: ${AUTH_APPLE_CLIENT_ID}
    issuers: https://appleid.apple.com
    jwk-url: https://appleid.apple.com/auth/keys

otp:
  encryption:
    key: ${OTP_ENCRYPTION_KEY}

  cleaner-job:
    cron: "0 20 * * * *"
    fetch-count: 10
    max-iteration: 50

  email:
    ttl: 3m
    length: 6
    attempt-count: 3

email:
  sender-type: console # implement your email sender

ratelimit:
  ip-header-name: X-Forwarded-For
  trusted-proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
  policies:
    anonymous-login-success:
      ip:
        limit: 5
        window: 24h
      global:
        limit: 100
        window: 24h

    refresh-token-success:
      ip:
        limit: 3
        window: 60s

    refresh-token-fail:
      ip:
        limit: 5
        window: 24h

    apple-login-fail:
      ip:
        limit: 5
        window: 24h

    google-login-fail:
      ip:
        limit: 5
        window: 24h

    email-otp-requested:
      ip:
        limit: 3
        window: 1h
      user:
        limit: 3
        window: 24h
